### ISSUE TITLE
hotkey not working

### ISSUE THREAD

**Issue by OrangeCellRBX** [YoinkedYoink/xinex#3]
```python
#triggerbot_key = 'n'
aimbot_key = 'x'
closeui_key = 'p'
``` 

I have read the source code, the closegui hotkey is "P". I tried pressing the P key on the keyboard, but it doesn't work.

**Comment by YoinkedYoink** [comment]
Unless you are using an old version, to hide/show the ui use insert/ins.
If you are using an old version, that only works if you have the gui enabled.

Currently the aimbot will not work as arsenal slightly changed the colours, if you want edit the colours on lower_pink and upper_pink and create a pull request.
